- id: '1608086300101'
  alias: Stove Light Cooking Time
  description: ''
  trigger:
  - platform: time
    at: '18:00:00'
  condition: []
  action:
  - scene: scene.livingroom_relax
  mode: single
- id: '1613160140792'
  alias: Humidity Too Low
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: 53d4f83bc5fdd0709f1e49474cb7d86a
    entity_id: sensor.4_in_1_sensor_humidity
    domain: sensor
    below: 32
    above: 0
    for:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  condition: []
  action:
  - service: notify.mobile_app_drew_s_phone
    data:
      message: Humidity beyond threshold
  mode: single
- id: '1613160579606'
  alias: Test Motion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 53d4f83bc5fdd0709f1e49474cb7d86a
    entity_id: binary_sensor.4_in_1_sensor_home_security_motion_detection
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  condition: []
  action:
  - service: notify.mobile_app_drew_s_phone
    data:
      message: motion triggered
  mode: single
- id: '1617217837385'
  alias: Post Work
  description: ''
  trigger:
  - platform: time
    at: '17:00'
  condition: []
  action:
  - scene: scene.new_scene
  mode: single
- id: '1617899309846'
  alias: Late Night Motion in Caroline's Room
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 53d4f83bc5fdd0709f1e49474cb7d86a
    entity_id: binary_sensor.4_in_1_sensor_home_security_motion_detection
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  condition:
  - condition: sun
    after: sunset
  action:
  - scene: scene.caroline_s_late_night_motion
  mode: single
- id: '1617899442747'
  alias: Motion Stopped In Caroline's room
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 53d4f83bc5fdd0709f1e49474cb7d86a
    entity_id: binary_sensor.4_in_1_sensor_home_security_motion_detection
    domain: binary_sensor
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - scene: scene.caroline_dark_room
  mode: single
- id: '1617900972692'
  alias: Daytime In Caroline's Room
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 53d4f83bc5fdd0709f1e49474cb7d86a
    entity_id: binary_sensor.4_in_1_sensor_home_security_motion_detection
    domain: binary_sensor
  condition:
  - condition: sun
    before: sunset
    after: sunrise
    before_offset: 00:20:00
  action:
  - scene: scene.carolines_room_daytime
  mode: single
- id: '1617928650822'
  alias: Early Morning Motion in Caroline's Room
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 53d4f83bc5fdd0709f1e49474cb7d86a
    entity_id: binary_sensor.4_in_1_sensor_home_security_motion_detection
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  condition:
  - condition: sun
    before: sunrise
  action:
  - scene: scene.caroline_s_late_night_motion
  mode: single
- id: '1618422074174'
  alias: Bedtime
  description: ''
  trigger:
  - platform: time
    at: '23:00'
  condition: []
  action:
  - scene: scene.bedtime
  mode: single
- id: '1618599001458'
  alias: New Automation
  description: ''
  trigger:
  - platform: event
    event_type: ''
  condition: []
  action:
  - service: tts.cloud_say
    data:
      entity_id: media_player.den
      message: 'welcome home drew, you are the best! i love you! will you marry me? '
  mode: single
- id: '1621456103626'
  alias: Low Temp Trigger
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.t6_pro_z_wave_programmable_thermostat_air_temperature
    from: '69'
    to: '68'
    for: 00:01:00
  condition: []
  action:
  - device_id: a77ad9a8b22cda280b49d225dbf5a937
    domain: climate
    entity_id: climate.t6_pro_z_wave_programmable_thermostat
    type: set_hvac_mode
    hvac_mode: heat
  - service: zwave_js.set_value
    target:
      entity_id: climate.t6_pro_z_wave_programmable_thermostat
    data:
      command_class: '67'
      property: setpoint
      value: 69
      property_key: '1'
  mode: single
- id: '1621457487594'
  alias: High Temp Trigger
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: climate.t6_pro_z_wave_programmable_thermostat
    attribute: current_temperature
    above: '73'
    for: 00:00:05
  condition: []
  action:
  - device_id: a77ad9a8b22cda280b49d225dbf5a937
    domain: climate
    entity_id: climate.t6_pro_z_wave_programmable_thermostat
    type: set_hvac_mode
    hvac_mode: cool
  - service: zwave_js.set_value
    target:
      entity_id: climate.t6_pro_z_wave_programmable_thermostat
    data:
      command_class: '67'
      property: setpoint
      property_key: '2'
      value: 73
  - service: notify.mobile_app_drew_s_phone
    data:
      message: AC is now on and set to 73
      title: Thermostat
  mode: single
